name: Run syntax tests
description: Run syntax tests
inputs:
  package-name:
    description: Package name. Derived from repo name if empty.
    default: ''
  compatibility:
    description: Test regex compatibility of the new syntax engine.
    default: true
runs:
  using: 'composite'
  steps:
    - run: |
        PACKAGE="${{ inputs.package-name }}"
        PACKAGE="${PACKAGE:-${GITHUB_REPOSITORY#*/}}"

        python3 "$GITHUB_ACTION_PATH/../../scripts/run_tests.py" "$PACKAGE" --syntax-test

        if [ "${{ inputs.compatibility }}" == "true" ]; then
          python3 "$GITHUB_ACTION_PATH/../../scripts/run_tests.py" "$PACKAGE" --syntax-compatibility
        fi
      shell: bash
