version: 2.1

# if you are looking for a working example
# refer to https://github.com/randy3k/UnitTesting-example/blob/master/.circleci/config.yml

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-linux:
    docker:
      - image: sublimetext/unittesting
    steps:
      - checkout
      - run: sh -e /etc/init.d/xvfb start
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh sbin/circleci.sh bootstrap
          sh sbin/circleci.sh install_color_scheme_unit
          sh sbin/circleci.sh install_package_control
          sh sbin/circleci.sh run_tests --coverage
      - run: |
          apt-get update
          apt-get install python3-pip -y
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov

  build-macos:
    macos:
      xcode: "11.4.0"
    steps:
      - checkout
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh sbin/circleci.sh bootstrap
          sh sbin/circleci.sh install_color_scheme_unit
          sh sbin/circleci.sh install_package_control
          sh sbin/circleci.sh run_tests --coverage
      - run: |
          pip3 install coverage==4.5.4 codecov==2.0.15
          codecov

  build-windows:
    executor: win/default
    steps:
      - checkout
      - run: |
          ./sbin/circleci.ps1 "bootstrap" -verbose
          ./sbin/circleci.ps1 "install_color_scheme_unit" -verbose
          ./sbin/circleci.ps1 "install_package_control" -verbose
          ./sbin/circleci.ps1 "run_tests" -coverage -verbose
      - run: |
          pip install coverage==4.5.4 codecov==2.0.15
          codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-linux
      - build-macos
      # ciricleci keeps saying we are out of credits, disable it for now
      - build-windows
