name: Run UnitTesting
description: Run UnitTesting
inputs:
  coverage:
    description: Run with coverage report
    required: true
    default: false
runs:
  using: 'composite'
  steps:
    - run: |
        . $GITHUB_ACTION_PATH/../../scripts/utils.sh
        if [ "${{ inputs.coverage }}" == "true" ]; then
          python3 "$STP/UnitTesting/scripts/run_tests.py" $PACKAGE --coverage
        else
          python3 "$STP/UnitTesting/scripts/run_tests.py" $PACKAGE
        fi
      shell: bash
