name: Run UnitTesting
description: Run UnitTesting
inputs:
  package-name:
    description: Package name. Derived from setup step if empty.
    default: ''
  coverage:
    description: Run with coverage report
    required: true
    default: false
  codecov-upload:
    description: Deprecated. Upload coverage report to codecov.
    required: true
    default: false
runs:
  using: 'composite'
  steps:
    - run: |
        # Run UnitTests
        PACKAGE_FROM_INPUTS="${{ inputs.package-name }}"
        PACKAGE="${PACKAGE_FROM_INPUTS:-$PACKAGE}"

        if [ "${{ inputs.coverage }}" == "true" ]; then
          python "$GITHUB_ACTION_PATH/run_tests.py" "$PACKAGE" --coverage
        else
          python "$GITHUB_ACTION_PATH/run_tests.py" "$PACKAGE"
        fi
      shell: bash
    - if: inputs.codecov-upload == 'true'
      run: |
        # Run UnitTests
        echo "The setting `codecov-upload` is deprecated."
        echo "Please call the action `codecov/codecov-action` directly".
      shell: bash
    - if: inputs.codecov-upload == 'true'
      uses: codecov/codecov-action@v4
