name: Run UnitTesting
description: Run UnitTesting
inputs:
  package-name:
    description: Package name. Derived from repo name if empty.
    default: ''
  coverage:
    description: Run with coverage report
    required: true
    default: false
  codecov-upload:
    description: Upload coverage report to codecov.
    required: true
    default: false
runs:
  using: 'composite'
  steps:
    - run: |
        . $GITHUB_ACTION_PATH/../../scripts/utils.sh

        PACKAGE_TO_TEST="${{ inputs.package-name }}"
        PACKAGE_TO_TEST=${PACKAGE_TO_TEST:-$PACKAGE}

        if [ "${{ inputs.coverage }}" == "true" ]; then
          python3 "$GITHUB_ACTION_PATH/../../scripts/run_tests.py" $PACKAGE_TO_TEST --coverage
        else
          python3 "$GITHUB_ACTION_PATH/../../scripts/run_tests.py" $PACKAGE_TO_TEST
        fi
      shell: bash
    - if: inputs.codecov == 'true'
      run: |
        if [ -f ./.coverage ]; then
          pip3 install coverage==4.5.4
          coverage xml -o coverage.xml
        fi
      shell: bash
    - if: inputs.codecov == 'true'
      uses: codecov/codecov-action@v2
