name: Publish Docker image

on:
  push:
    branches: [main, master]
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yaml'
  schedule:
    - cron: "22 2 * * 2"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push x64 image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          tags: sublimetext/unittesting:latest,sublimetext/unittesting:x64

      - name: Build and push x32 image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          build-args: |
            arch=i386
          tags: sublimetext/unittesting:x32
