name: merge-to-v1

on:
  push:
    tags:
      - '*'

jobs:
  merge-to-v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        with:
          script: |
            await github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "v1",
              head: context.sha,
              commit_message: "Merge to v1"
            });
