name: merge-v1

on:
  push:
    tags:
      - '*'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: v1
          commit_message_template: 'Merged {source_ref} into {target_branch}'
