# if you are looking for a working example
# refer to https://github.com/randy3k/UnitTesting-example/blob/master/.github/workflows/test.yaml

name: test

on: [push, pull_request]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}


  test-install-dependencies:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: "./actions/setup"
        with:
          install-package: false
          extra-packages: |
            sublimelsp/lsp_utils
            sublimelsp/LSP-pyright
      - run: |
          ls -l $SUBLIME_TEXT_PACKAGES/lsp_utils
        shell: bash
      - uses: "./actions/run-tests"
        with:
          package-name: lsp_utils
