# if you are looking for a working example
# refer to https://github.com/randy3k/UnitTesting-example/blob/master/.github/workflows/test.yaml

name: test

on: [push, pull_request]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  # test against dev version of UnitTesting
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        st-version: [3, 4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: "./actions/setup"
        with:
          sublime-text-version: ${{ matrix.st-version }}
          install-unittesting: false
      - uses: "./actions/run-tests"
        with:
          coverage: true
          codecov-upload: true

  # test against latest released UnitTesting
  test-actions-aginst-latest:
    strategy:
      fail-fast: false
      matrix:
        st-version: [3, 4]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: "./actions/setup"
        with:
          sublime-text-version: ${{ matrix.st-version }}
          install-package: false
      - uses: "./actions/run-tests"

  test-install-extra-packages:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: "./actions/setup"
        with:
          install-package: false
          install-unittesting: false
          extra-packages: |
            SublimeText/UnitTesting
            randy3k/UnitTesting-example@master
      - uses: "./actions/run-tests"
        with:
          package-name: UnitTesting-example
